### ISSUE TITLE
Use vawy line instead of background decoration?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab_spellchecker#13]
Vawy lines are the default way of highlighting errors in modern text editors. This extension however, uses the vim-like background styling (which is also nice), but might not be intuitive for some users; I find it a little bit distracting and would prefer the red vawy line instead.

I managed to get vawy lines by modifying the styles.css:

![Screenshot from 2019-04-21 19-43-23](https://user-images.githubusercontent.com/5832902/56474147-c290e780-646d-11e9-9ff4-f452f5b20f64.png)

```css
.CodeMirror .cm-spell-error:not(.cm-url):not(.cm-tag):not(.cm-word) {
     text-decoration-line: underline;
     text-decoration-style: wavy;
     text-decoration-color: red;
     /* For Chrome */
     text-decoration-skip-ink: none;
}
```

A more browser-independent version could use background images, but the above one is probably more light-weight and performant. Currently the text-decoration styling is supported for [75-89% of users globally](https://caniuse.com/#search=text-decoration-style) (thouh the figure should be higher for people who work with Jupyter as I expect such users to be aware of risks of using outdated browsers).

If I open a PR, would you consider merging it, or are there reasons for keeping the current red background instead?
